<a href="https://colab.research.google.com/github/YoshiyukiKono/langchain_for_beginners/blob/main/2b_RAG_advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LangChain with Astra DB & Open AI

## Environment Setup
It is expected to use GPU when using the embedding model. Change the setting from the menu as follows: Runtime > Change runtime type > Hardware accelerator: `GPU`

## Package Install

In [ ]:
!pip install langchain
!pip install openai
!pip install tiktoken

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 19.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.0/40.0 kB 4.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.4/49.4 kB 4.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.0/77.0 kB 1.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 19.7 MB/s eta 0:00:00


In [ ]:
!pip install cassandra-driver

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 69.7 MB/s eta 0:00:00


## Astra

In [ ]:
!wget -O secure-connect-demo.zip "https://..."

--2023-09-01 05:03:54--  https://datastax-cluster-config-prod.s3.us-east-2.amazonaws.com/d5556151-ea9a-4309-8be3-b8ea2b1cd03d-1/secure-connect-demo.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA2AIQRQ76S2JCB77W%2F20230901%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20230901T050340Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=7db1257a20828e206535d85e46ffdfe26c4fe1166781a157033bbaac549b23c3
Resolving datastax-cluster-config-prod.s3.us-east-2.amazonaws.com (datastax-cluster-config-prod.s3.us-east-2.amazonaws.com)... 3.5.131.128, 52.219.95.34, 52.219.179.34, ...
Connecting to datastax-cluster-config-prod.s3.us-east-2.amazonaws.com (datastax-cluster-config-prod.s3.us-east-2.amazonaws.com)|3.5.131.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12247 (12K) [application/zip]
Saving to: ‘secure-connect-demo.zip’

secure-connect-demo 100%[===================>]  11.96K  --.-KB/s    in 0s      

2023-09-01 05:03:54 (119 MB/s) - ‘secure-conne

In [ ]:
!wget -O secure-connect-demo.zip "https://datastax-cluster-config-prod.s3.us-east-2.amazonaws.com/d5556151-ea9a-4309-8be3-b8ea2b1cd03d-1/secure-connect-demo.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA2AIQRQ76S2JCB77W%2F20231012%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20231012T042432Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=31a24fdca14a3d5fbfb56fb46404da6d311d2638c4685d644f96dea80804c25b"

--2023-10-12 04:24:48--  https://datastax-cluster-config-prod.s3.us-east-2.amazonaws.com/d5556151-ea9a-4309-8be3-b8ea2b1cd03d-1/secure-connect-demo.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA2AIQRQ76S2JCB77W%2F20231012%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20231012T042432Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=31a24fdca14a3d5fbfb56fb46404da6d311d2638c4685d644f96dea80804c25b
Resolving datastax-cluster-config-prod.s3.us-east-2.amazonaws.com (datastax-cluster-config-prod.s3.us-east-2.amazonaws.com)... 52.219.111.26, 3.5.129.167, 3.5.129.110, ...
Connecting to datastax-cluster-config-prod.s3.us-east-2.amazonaws.com (datastax-cluster-config-prod.s3.us-east-2.amazonaws.com)|52.219.111.26|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12247 (12K) [application/zip]
Saving to: ‘secure-connect-demo.zip’

secure-connect-demo 100%[===================>]  11.96K  --.-KB/s    in 0s      

2023-10-12 04:24:48 (133 MB/s) - ‘secure-conn

In [ ]:
SECURE_CONNECT_BUNDLE_PATH = 'secure-connect-demo.zip'

In [ ]:
import getpass

ASTRA_CLIENT_ID = getpass.getpass()

··········


In [ ]:

ASTRA_CLIENT_SECRET = getpass.getpass()

··········


In [ ]:
from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider

cloud_config= {
  'secure_connect_bundle': SECURE_CONNECT_BUNDLE_PATH
}
auth_provider = PlainTextAuthProvider(ASTRA_CLIENT_ID, ASTRA_CLIENT_SECRET)
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
session = cluster.connect()

row = session.execute("select release_version from system.local").one()
if row:
  print(row[0])
else:
  print("An error occurred.")

ERROR:cassandra.connection:Closing connection <AsyncoreConnection(135353235378080) d5556151-ea9a-4309-8be3-b8ea2b1cd03d-us-east1.db.astra.datastax.com:29042:7930db73-72b7-4f36-9969-954647aba210> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"


4.0.11-2ea733607f3c


In [ ]:
YOUR_KEYSPACE = 'bookstore'
session.set_keyspace(YOUR_KEYSPACE)
session

### DATA

In [ ]:
%%writefile books.csv
ID,title,author,publisher,price,year,description
001,ネットワークセキュリティ入門,山田太郎,技術書典,4500,2021,ネットワークセキュリティの基本原則と実践的な手法に焦点を当てた入門書。
002,ビジネスデータ分析の基礎,田中花子,ビジネスブックス,3800,2020,ビジネスにおけるデータ分析の基本的な手法とツールの使い方を解説。
003,クラウドアーキテクチャデザイン,鈴木次郎,技術出版株式会社,5500,2022,クラウドネイティブなアプリケーションのアーキテクチャデザインとベストプラクティスを詳細に解説。
004,金融取引のアルゴリズム,林美香,データ出版社,5200,2019,金融市場におけるアルゴリズムトレーディングの基本原則と実践手法に焦点を当てた実践的なガイド。
005,人事マネジメントの実践,佐藤健太,ビジネスパートナーズ,4800,2020,組織内の人材マネジメントに関する基本的な原則と実践的な手法を紹介。
006,自然言語処理入門,伊藤さやか,技術書典,4200,2021,自然言語処理の基本概念から、実践的なテキストデータ処理手法までを解説。
007,マーケティング戦略の立案,山口直樹,ビジネスブックス,3600,2018,市場分析、セグメンテーション、ポジショニングなど、マーケティング戦略の構築手法を学ぶ。
008,ディープラーニングアプリケーション,田村徹,技術出版株式会社,6500,2019,ディープラーニングを使用した実践的なアプリケーション開発手法に焦点を当てた実践書。
009,投資ポートフォリオ管理,高橋優一,金融情報出版,3700,2020,効果的な投資ポートフォリオの構築と管理に関する手法を解説。
010,サイバーセキュリティ実践ガイド,中村あや,技術書典,4800,2021,サイバーセキュリティの基本から、脆弱性診断、セキュリティ対策までを詳細に解説。
011,ビジネスリーダーシップの原則,大塚和夫,ビジネスパートナーズ,4200,2020,ビジネスにおけるリーダーシップの基本原則と実践的なリーダーシップスキルの向上を目指す手法を紹介。
012,コンピュータネットワークの基礎,西村さゆり,技術書典,3500,2022,コンピュータネットワークの基本概念から、実践的なネットワーク設計までを解説。
013,ビジネスプロセス最適化,小林太郎,ビジネスブックス,4600,2019,ビジネスプロセスの最適化手法とツールを駆使して企業の効率を向上させる手法を詳細に解説。
014,データウェアハウス設計入門,川上美香,データ出版社,5000,2021,データウェアハウスの基本概念から、実践的な設計手法までを解説。
015,マネジャーのためのコーチング,森田健太,ビジネスパートナーズ,3900,2018,リーダーシップとコーチングの基本原則と実践的なスキル向上のための手法を解説。
016,組み込みシステム開発ガイド,伊藤美和,技術出版株式会社,5500,2019,組み込みシステムの開発手法とデバッグテクニックに焦点を当てた実践的なガイド。
17,ディープラーニング実践入門,岡田淳,技術出版株式会社,4800,2022,ディープラーニングの基本理論から実践的な応用までを解説。
18,ビジネスプロセス改善ガイド,松本美香,ビジネスブックス,3500,2021,効果的なビジネスプロセス改善手法とツールを紹介。
19,Pythonデータサイエンス,田中健太,技術書典,4200,2020,Pythonを使用したデータサイエンスの基本と実践手法を学ぶ。
20,金融工学入門,林美香,データ出版社,5500,2019,金融商品の設計と価格付けに関する基本原則と数学的手法の解説。
21,チームリーダーシップの手引き,佐藤健太,ビジネスパートナーズ,4000,2020,効果的なチームリーダーシップの構築と維持に関するガイド。
22,React.js開発入門,伊藤さやか,技術書典,3800,2022,React.jsを使用したモダンなWebアプリケーションの開発手法を学ぶ。
23,戦略的マーケティング,山口直樹,ビジネスブックス,4500,2018,市場分析と戦略の構築に焦点を当てたマーケティング戦略のガイド。
24,機械学習プロジェクト管理,田村徹,技術出版株式会社,4900,2019,機械学習プロジェクトの計画と実行に関する手法を解説。
25,投資戦略の戦術,高橋優一,金融情報出版,3600,2021,リスク管理と効果的な投資戦略の構築に焦点を当てた投資戦略の戦術を解説。
26,サイバーセキュリティ対策,中村あや,技術書典,4300,2021,サイバーセキュリティの基本概念と対策手法を解説。
27,効果的なプロジェクトマネジメント,大塚和夫,ビジネスパートナーズ,4100,2020,プロジェクトの計画と実行に関する基本原則と実践的な手法を学ぶ。
28,データウェアハウス設計と実践,川上美香,データ出版社,5200,2021,データウェアハウスの設計と実践的なデータ統合手法を解説。
29,マーケットリサーチ入門,森田健太,ビジネスブックス,3700,2018,効果的なマーケットリサーチの実施とデータ分析手法を学ぶ。
30,クラウドセキュリティベストプラクティス,西村さゆり,技術出版株式会社,4700,2019,クラウド環境でのセキュリティのベストプラクティスを解説。
31,データサイエンティストのための統計学,小林太郎,データ書典,4400,2020,データサイエンスにおける統計学の基本と高度な手法までを解説。
32,リーダーシップ開発プログラム,中村美和,ビジネスパートナーズ,3900,2021,リーダーシップスキルの開発とチームビルディングの手法を学ぶ。
33,モバイルアプリケーション開発,高橋健一,技術書典,5000,2019,モバイルアプリケーションの開発手法とデザイン原則に焦点を当てた実践的なガイド。
34,投資ポートフォリオ戦略,田村美香,金融情報出版,4100,2020,リスク管理と効果的なポートフォリオの構築に焦点を当てた投資戦略の構築手法を解説。
35,サイバーセキュリティ実践入門,伊藤健太,技術書典,4600,2021,サイバーセキュリティの基本から、実践的な対策手法までを詳細に解説。
36,量子コンピューティング入門,岡本太郎,技術書典,5800,2022,量子コンピューティングの基礎理論から実践的な応用までを解説。
37,組織開発と変革マネジメント,村田花子,ビジネスブックス,4200,2021,組織の成熟度と変革マネジメントの手法に焦点を当てた実践的なガイド。
38,Javaマイクロサービスアーキテクチャ,佐々木健太,技術出版株式会社,4800,2020,Javaを使用したマイクロサービスアーキテクチャの基本と設計手法を学ぶ。
39,新時代のプロダクトマネジメント,林さやか,ビジネスパートナーズ,5500,2019,デジタルプロダクトのマネジメントにおける新たな手法とアプローチを解説。
40,ネットワークセキュリティ実践ガイド,高橋徹,技術書典,4600,2020,ネットワークセキュリティの実践的な対策手法とセキュアなネットワーク構築手法を学ぶ。
41,スタートアップのための財務戦略,伊東美和,ビジネスブックス,4000,2021,スタートアップ企業の財務戦略と資金調達の手法に焦点を当てたガイド。
42,自然言語処理と機械翻訳,山岸直樹,技術出版株式会社,5300,2018,自然言語処理と機械翻訳の基本原則と応用手法を学ぶ。
43,企業価値の最大化,佐野美香,データ出版社,4900,2019,企業価値の向上と最大化に向けた戦略と実践手法を解説。
44,データサイエンスとビジネス分析,鈴木健一,金融情報出版,3600,2020,データサイエンスとビジネスアナリティクスの基本概念と手法を学ぶ。
45,クラウドセキュリティポリシー,中川美和,技術書典,4400,2021,クラウド環境でのセキュリティポリシーの設計と実践手法に焦点を当てた実践ガイド。
46,リーダーシップ心理学,大西美香,ビジネスパートナーズ,4100,2018,リーダーシップと心理学の関連性と、組織内での実践手法を解説。
47,フロントエンド開発ベストプラクティス,田島健太,技術出版株式会社,4900,2019,モダンなフロントエンド開発のベストプラクティスと設計原則に焦点を当てた実践的なガイド。
48,投資リスク管理戦略,堀田直樹,金融情報出版,4200,2020,効果的な投資リスク管理戦略とポートフォリオの構築手法を解説。
49,セキュアなソフトウェア開発,大久保美和,技術書典,5500,2021,セキュアなソフトウェアの設計と実装に関する基本原則と手法を学ぶ。
50,ビジネスインテリジェンス基礎,小川美香,データ出版社,4700,2020,ビジネスインテリジェンスの基本的な原則とデータ分析手法を解説。
51,デジタルマーケティング入門,石田健太,ビジネスブックス,4000,2022,デジタル時代におけるマーケティング戦略と実践的なデジタル広告手法に焦点を当てた入門書。
52,モバイルセキュリティベストプラクティス,中山さやか,技術書典,4400,2022,モバイルアプリケーションのセキュリティ設計と対策手法を解説。
53,ビジネスプランの作成法,渡辺徹,ビジネスパートナーズ,3800,2019,効果的なビジネスプランの作成と実行に向けた手法を学ぶ。
54,クラウドネイティブアーキテクチャ,吉田太郎,技術出版株式会社,5200,2022,クラウドネイティブなアプリケーションの設計と構築に関する包括的なガイド。
55,組織学習の手法,石井花子,ビジネスブックス,4300,2021,組織が持続的に学習し成長するための手法と実践例を解説。
56,JavaScriptデザインパターン,小林次郎,技術書典,4600,2020,JavaScriptにおけるデザインパターンと実践的なプログラミング手法を学ぶ。
57,デジタルトランスフォーメーション戦略,鈴木美和,ビジネスパートナーズ,5400,2019,組織全体でのデジタルトランスフォーメーション戦略の策定と実行に関するガイド。
58,ネットワークプログラミング実践,田村健太,技術書典,4800,2020,ネットワークプログラミングの基本概念から、実践的なアプリケーション開発までを解説。
59,マーケットセグメンテーション,山本直樹,ビジネスブックス,4000,2021,効果的なマーケットセグメンテーションの手法と市場分析に焦点を当てた入門書。
60,サーバレスアーキテクチャ設計,田中美香,技術出版株式会社,5000,2018,サーバレスなアプリケーションの設計とデプロイに関する手法を解説。
61,人材育成プログラム,高橋直樹,ビジネスパートナーズ,3700,2019,組織内での効果的な人材育成プログラムの構築と実践手法を学ぶ。
62,Python機械学習実践ガイド,西村美和,技術書典,5300,2021,Pythonを使用した機械学習の基本理論から実践的な応用までを解説。
63,金融市場データ分析,堀田太郎,データ出版社,4600,2022,金融市場データの分析手法と取引戦略に焦点を当てた実践ガイド。
64,サイバーセキュリティリーダーシップ,矢田美香,技術出版株式会社,4800,2019,組織全体でのサイバーセキュリティリーダーシップの原則と実践手法を解説。
65,効果的なマーケティングコミュニケーション,小野次郎,ビジネスブックス,4200,2020,ターゲットに向けた効果的なマーケティングコミュニケーション戦略を解説。
66,データエンジニアリング入門,松井あや,技術書典,4900,2021,データエンジニアリングの基本概念と実践的なデータ処理手法を学ぶ。
67,戦略的イノベーションマネジメント,大木徹,ビジネスパートナーズ,5500,2020,企業における戦略的なイノベーションマネジメントの手法と実践例を解説。
68,ソフトウェアアーキテクチャ設計,藤田健一,技術出版株式会社,5100,2019,ソフトウェアアーキテクチャの基本原則と設計手法に焦点を当てた実践的なガイド。
69,投資ポートフォリオ最適化,石井さやか,金融情報出版,4300,2020,リスクとリターンのバランスを考慮した投資ポートフォリオ最適化の手法を解説。
70,マイクロサービスアーキテクチャ実践,森下太郎,技術出版株式会社,5200,2022,マイクロサービスアーキテクチャの実践的な設計と運用に関するガイド。
71,戦略的リーダーシップ,大橋美和,ビジネスブックス,4500,2021,組織戦略とリーダーシップの統合に焦点を当てた戦略的リーダーシップのガイド。
72,データウェアハウス最適化,田口健太,技術書典,4700,2020,データウェアハウスの最適化手法とパフォーマンスチューニングに関する実践的な知識。
73,プログラマのためのアルゴリズム,小山直樹,技術出版株式会社,3800,2019,プログラマ向けの基本的なアルゴリズムとデータ構造に焦点を当てた解説書。
74,デジタル戦略の構築,鈴木花子,ビジネスパートナーズ,5100,2019,デジタル時代におけるビジネス戦略の構築手法と実践例を解説。
75,ネットワークセキュリティベストプラクティス,高田徹,技術書典,4400,2022,ネットワークセキュリティのベストプラクティスと脅威対策に関するガイド。
76,人材評価と報酬戦略,小林美和,ビジネスブックス,4300,2021,組織内での効果的な人材評価と報酬戦略の構築手法を学ぶ。
77,リアクティブプログラミング入門,西野健太,技術出版株式会社,4800,2020,リアクティブなアプリケーション開発の基本理論と実践手法を解説。
78,データサイエンスと医療,大谷花子,データ出版社,5400,2021,医療データの解析とデータサイエンスの応用に焦点を当てた入門書。
79,クラウドアーキテクト設計,佐々木徹,技術書典,5000,2022,クラウドシステムのアーキテクト設計とベストプラクティスに関するガイド。
80,ビジネスエシックス,中川美和,ビジネスパートナーズ,3700,2020,ビジネス環境における倫理とエシックスの基本原則と実践的なガイド。
81,機械学習モデル解釈,高木健太,技術書典,4600,2019,機械学習モデルの解釈手法とモデルの透明性向上に焦点を当てた実践書。
82,セキュアなWeb開発,石崎さやか,技術出版株式会社,4300,2021,セキュアなWebアプリケーションの開発手法とセキュリティ対策に関するガイド。
83,デジタルマーケティング戦略,小野徹,ビジネスブックス,4900,2020,デジタルマーケティング戦略の立案と実行に関する実践的な手法を解説。
84,サーバーサイド開発入門,伊東美香,技術書典,4100,2022,サーバーサイド開発の基本概念から、実践的なアプリケーション開発までを解説。
85,データアーキテクチャ設計,松永直樹,データ出版社,5200,2019,データアーキテクチャの設計と実践的なデータ管理手法を学ぶ。
86,クラウドセキュリティアーキテクチャ,田辺美香,技術出版株式会社,5300,2022,クラウド環境におけるセキュリティアーキテクチャの設計と実践手法を解説。
87,リーダーシップ開発プログラム,小野さやか,ビジネスブックス,4100,2021,リーダーシップスキルの開発とチームビルディングの手法を学ぶ。
88,自然言語処理とテキストマイニング,村上健太,技術書典,4700,2020,自然言語処理とテキストマイニングの基本原則と実践手法を学ぶ。
89,デジタル戦略の実践,渡辺花子,ビジネスパートナーズ,5500,2019,デジタル時代におけるビジネス戦略の実践的な構築と実行に関するガイド。
90,フロントエンド開発ベストプラクティス,石井美和,技術出版株式会社,4800,2020,モダンなフロントエンド開発のベストプラクティスと設計原則に焦点を当てた実践的なガイド。
91,イノベーションマネジメント,佐々木太郎,ビジネスブックス,4300,2021,組織内での効果的なイノベーションマネジメントの手法と実践例を解説。
92,Pythonデータサイエンティスト養成,矢田さやか,技術出版株式会社,5100,2018,Pythonを使用したデータサイエンスの基本から実践までの養成ガイド。
93,金融市場リスク管理,山口健太,データ出版社,4900,2019,金融市場におけるリスク管理の基本原則と実践手法を解説。
94,マーケティングデータ分析,大塚美香,金融情報出版,4200,2020,効果的なマーケティングデータ分析の手法と意思決定への応用に焦点を当てた実践ガイド。
95,サイバーセキュリティリスクマネジメント,小川さやか,技術書典,4600,2022,サイバーセキュリティリスクの評価とマネジメントの手法に焦点を当てたガイド。
96,戦略的マーケティングプラン,松本美和,ビジネスパートナーズ,4700,2021,組織のビジョンと目標に基づく戦略的なマーケティングプランの構築手法を解説。
97,データサイエンスとビッグデータ,石田美香,技術書典,5300,2020,データサイエンスとビッグデータの基本原則から実践までの手法を学ぶ。
98,アジャイル開発プラクティス,吉田花子,技術出版株式会社,4000,2021,アジャイルなソフトウェア開発のプラクティスとスクラムの導入手法を解説。
99,サプライチェーンマネジメント,中村健太,データ出版社,5200,2022,効果的なサプライチェーンマネジメントの原則と実践手法を解説。
100,量子コンピュータ応用,田島美和,技術書典,4900,2020,量子コンピュータの応用領域と実践的な利用事例に焦点を当てたガイド。
101,エンタープライズアーキテクチャ,小林花子,ビジネスパートナーズ,4400,2019,エンタープライズ全体のアーキテクチャ設計と最適化手法に関する実践ガイド。
102,プロジェクトポートフォリオマネジメント,松井直樹,技術出版株式会社,5000,2020,プロジェクトポートフォリオの戦略的なマネジメント手法と実践例を解説。
103,マネジメント情報システム,大木美和,データブックス,4600,2021,組織内でのマネジメント情報システムの設計と運用に焦点を当てたガイド。






Writing books.csv


In [ ]:

!head books.csv

ID,title,author,publisher,price,year,description
001,ネットワークセキュリティ入門,山田太郎,技術書典,4500,2021,ネットワークセキュリティの基本原則と実践的な手法に焦点を当てた入門書。
002,ビジネスデータ分析の基礎,田中花子,ビジネスブックス,3800,2020,ビジネスにおけるデータ分析の基本的な手法とツールの使い方を解説。
003,クラウドアーキテクチャデザイン,鈴木次郎,技術出版株式会社,5500,2022,クラウドネイティブなアプリケーションのアーキテクチャデザインとベストプラクティスを詳細に解説。
004,金融取引のアルゴリズム,林美香,データ出版社,5200,2019,金融市場におけるアルゴリズムトレーディングの基本原則と実践手法に焦点を当てた実践的なガイド。
005,人事マネジメントの実践,佐藤健太,ビジネスパートナーズ,4800,2020,組織内の人材マネジメントに関する基本的な原則と実践的な手法を紹介。
006,自然言語処理入門,伊藤さやか,技術書典,4200,2021,自然言語処理の基本概念から、実践的なテキストデータ処理手法までを解説。
007,マーケティング戦略の立案,山口直樹,ビジネスブックス,3600,2018,市場分析、セグメンテーション、ポジショニングなど、マーケティング戦略の構築手法を学ぶ。
008,ディープラーニングアプリケーション,田村徹,技術出版株式会社,6500,2019,ディープラーニングを使用した実践的なアプリケーション開発手法に焦点を当てた実践書。
009,投資ポートフォリオ管理,高橋優一,金融情報出版,3700,2020,効果的な投資ポートフォリオの構築と管理に関する手法を解説。


In [ ]:
import pandas as pd
#CSVファイルの読み込み
df = pd.read_csv("books.csv")
print(df)
print(type(df))

      ID                title author   publisher  price  year  \
0      1       ネットワークセキュリティ入門   山田太郎        技術書典   4500  2021   
1      2         ビジネスデータ分析の基礎   田中花子    ビジネスブックス   3800  2020   
2      3      クラウドアーキテクチャデザイン   鈴木次郎    技術出版株式会社   5500  2022   
3      4          金融取引のアルゴリズム    林美香      データ出版社   5200  2019   
4      5          人事マネジメントの実践   佐藤健太  ビジネスパートナーズ   4800  2020   
..   ...                  ...    ...         ...    ...   ...   
98    99       サプライチェーンマネジメント   中村健太      データ出版社   5200  2022   
99   100           量子コンピュータ応用   田島美和        技術書典   4900  2020   
100  101      エンタープライズアーキテクチャ   小林花子  ビジネスパートナーズ   4400  2019   
101  102  プロジェクトポートフォリオマネジメント   松井直樹    技術出版株式会社   5000  2020   
102  103         マネジメント情報システム   大木美和     データブックス   4600  2021   

                                         description  
0                ネットワークセキュリティの基本原則と実践的な手法に焦点を当てた入門書。  
1                   ビジネスにおけるデータ分析の基本的な手法とツールの使い方を解説。  
2    クラウドネイティブなアプリケーションのアーキテクチャデザインとベストプラクティスを詳細に解説。  

## Enbeddings Preperation

### Target Selection


In [ ]:
descriptions = df["description"]

In [ ]:
type(descriptions)

pandas.core.series.Series

In [ ]:
targets = descriptions.tolist()
type(targets)

list

### LangChain Preparation

In [ ]:
import langchain
# Enable langchain debug mode
langchain.debug = True
from langchain.agents.agent_toolkits import create_retriever_tool, create_conversational_retrieval_agent
from langchain.chat_models import ChatOpenAI
from langchain.embeddings import OpenAIEmbeddings
from langchain.callbacks import StreamlitCallbackHandler
from langchain.schema import BaseRetriever, Document, SystemMessage

### OpenAI

In [ ]:
import os
import openai
import getpass

os.environ["OPENAI_API_KEY"] = getpass.getpass()
openai.api_key = os.getenv("OPENAI_API_KEY")


··········


In [ ]:
embeddings = OpenAIEmbeddings()

# Part A: LangChain without CassIO

## DDL

In [ ]:
session.execute("""
DROP TABLE IF EXISTS book_openai;
        """
)

In [ ]:
session.execute("""DROP INDEX IF EXISTS idx_price_book_openai;""")
session.execute("""DROP INDEX IF EXISTS idx_year_book_openai;""")
session.execute("""DROP INDEX IF EXISTS idx_sem_vec_book_openai;""")
session.execute("""DROP TABLE IF EXISTS book_openai;""")

In [ ]:
session.execute("""
CREATE TABLE  book_openai (
id text,
title text,
author text,
publisher text,
price int,
year int,
description text,
sem_vec vector<float, 1536>,
PRIMARY KEY((author, publisher), title, id)
);
        """
)

In [ ]:
session.execute("CREATE CUSTOM INDEX idx_price_book_openai ON book_openai(price) USING 'org.apache.cassandra.index.sai.StorageAttachedIndex'")
session.execute("CREATE CUSTOM INDEX idx_year_book_openai ON book_openai(year) USING 'org.apache.cassandra.index.sai.StorageAttachedIndex'")
session.execute("CREATE CUSTOM INDEX idx_sem_vec_book_openai ON book_openai(sem_vec) USING 'org.apache.cassandra.index.sai.StorageAttachedIndex'")

## Data Load

In [ ]:
openai_embedding_params = []
for target in targets:
  openai_embedding_params.append(embeddings.embed_query(target))

In [ ]:
print(len(openai_embedding_params[0]))

1536


In [ ]:
df_openai = df.assign(sem_vec_openai=openai_embedding_params)
df_openai

ID                title author   publisher  price  year  \
0      1       ネットワークセキュリティ入門   山田太郎        技術書典   4500  2021   
1      2         ビジネスデータ分析の基礎   田中花子    ビジネスブックス   3800  2020   
2      3      クラウドアーキテクチャデザイン   鈴木次郎    技術出版株式会社   5500  2022   
3      4          金融取引のアルゴリズム    林美香      データ出版社   5200  2019   
4      5          人事マネジメントの実践   佐藤健太  ビジネスパートナーズ   4800  2020   
..   ...                  ...    ...         ...    ...   ...   
98    99       サプライチェーンマネジメント   中村健太      データ出版社   5200  2022   
99   100           量子コンピュータ応用   田島美和        技術書典   4900  2020   
100  101      エンタープライズアーキテクチャ   小林花子  ビジネスパートナーズ   4400  2019   
101  102  プロジェクトポートフォリオマネジメント   松井直樹    技術出版株式会社   5000  2020   
102  103         マネジメント情報システム   大木美和     データブックス   4600  2021   

                                         description  \
0                ネットワークセキュリティの基本原則と実践的な手法に焦点を当てた入門書。   
1                   ビジネスにおけるデータ分析の基本的な手法とツールの使い方を解説。   
2    クラウドネイティブなアプリケーションのアーキテクチャデザインとベストプラクティスを詳細に解説。   
3     金融市場におけるアルゴリズムトレーディングの基本原則と実践手法に焦点を当てた実践的なガイド。   
4                  組織内の人材マネジメントに関する基本的な原則と実践的な手法を紹介。   
..                                               ...   
98                    効果的なサプライチェーンマネジメントの原則と実践手法を解説。   
99                 量子コンピュータの応用領域と実践的な利用事例に焦点を当てたガイド。   
100             エンタープライズ全体のアーキテクチャ設計と最適化手法に関する実践ガイド。   
101               プロジェクトポートフォリオの戦略的なマネジメント手法と実践例を解説。   
102               組織内でのマネジメント情報システムの設計と運用に焦点を当てたガイド。   

                                        sem_vec_openai  
0    [0.007204100114747825, -0.004237320793178523, ...  
1    [-0.025559322470897573, -0.0025260976061453368...  
2    [-0.0009465341867541051, 0.006906319200066109,...  
3    [-0.015387951974107859, -0.004878941640886269,...  
4    [-0.014834928298503625, -0.001776199905848534,...  
..                                                 ...  
98   [-0.01104052982575181, -0.0013714996898895738,...  
99   [-0.006146749610493221, -0.0002058967107571266...  
100  [-0.0063821386799442666, 0.0032520339505585725...  
101  [-0.007437362717447291, -0.020178474857665135,...  
102  [-0.019953489318557453, -0.007048417161398362,...  

[103 rows x 8 columns]

In [ ]:
query = "INSERT INTO book_openai(id,title,author,publisher,price,year,description,sem_vec) VALUES (?,?,?,?,?,?,?,?)"
prepared = session.prepare(query)

In [ ]:
params_list = []
for index, row in df_openai.iterrows():
  params = [str(row['ID']),row['title'],row['author'],row['publisher'],row['price'],row['year'],row['description'],row['sem_vec_openai']]
  params_list.append(params)

In [ ]:

from cassandra.concurrent import execute_concurrent_with_args
execute_concurrent_with_args(session, prepared, params_list)

[ExecutionResult(success=True, result_or_exc=<cassandra.cluster.ResultSet object at 0x79149c09d120>),
 ExecutionResult(success=True, result_or_exc=<cassandra.cluster.ResultSet object at 0x79149c160bb0>),
 ExecutionResult(success=True, result_or_exc=<cassandra.cluster.ResultSet object at 0x79149c160730>),
 ExecutionResult(success=True, result_or_exc=<cassandra.cluster.ResultSet object at 0x79149c160550>),
 ExecutionResult(success=True, result_or_exc=<cassandra.cluster.ResultSet object at 0x79149c160850>),
 ExecutionResult(success=True, result_or_exc=<cassandra.cluster.ResultSet object at 0x79149c1605b0>),
 ExecutionResult(success=True, result_or_exc=<cassandra.cluster.ResultSet object at 0x79149c1606a0>),
 ExecutionResult(success=True, result_or_exc=<cassandra.cluster.ResultSet object at 0x79149c160040>),
 ExecutionResult(success=True, result_or_exc=<cassandra.cluster.ResultSet object at 0x79149c160160>),
 ExecutionResult(success=True, result_or_exc=<cassandra.cluster.ResultSet object a

In [ ]:
txt = 'データサイエンスについての書籍'

emb_query = embedding.embed_query(txt)
len(emb_query)

1536

In [ ]:
from cassandra.query import SimpleStatement
query = SimpleStatement("""
SELECT
similarity_cosine(sem_vec, %s) as similarity,
title, author, publisher, price, description
FROM book_openai
WHERE price > %s
ORDER BY sem_vec ANN OF %s LIMIT 5;
"""
)
price = 5000

results = session.execute(query, (emb_query, price, emb_query))
for row in results:
  print(row)

Row(similarity=0.9570698738098145, title='データサイエンスと医療', author='大谷花子', publisher='データ出版社', price=5400, description='医療データの解析とデータサイエンスの応用に焦点を当てた入門書。')
Row(similarity=0.9507706165313721, title='データサイエンスとビッグデータ', author='石田美香', publisher='技術書典', price=5300, description='データサイエンスとビッグデータの基本原則から実践までの手法を学ぶ。')
Row(similarity=0.9408993124961853, title='Pythonデータサイエンティスト養成', author='矢田さやか', publisher='技術出版株式会社', price=5100, description='Pythonを使用したデータサイエンスの基本から実践までの養成ガイド。')
Row(similarity=0.9366498589515686, title='ディープラーニングアプリケーション', author='田村徹', publisher='技術出版株式会社', price=6500, description='ディープラーニングを使用した実践的なアプリケーション開発手法に焦点を当てた実践書。')
Row(similarity=0.936499834060669, title='データアーキテクチャ設計', author='松永直樹', publisher='データ出版社', price=5200, description='データアーキテクチャの設計と実践的なデータ管理手法を学ぶ。')


In [ ]:
txt = '量子コンピュータ'

emb_query = embedding.embed_query(txt)
#emb_query.shape
len(emb_query)
from cassandra.query import SimpleStatement
query = SimpleStatement("""
SELECT
similarity_cosine(sem_vec, %s) as similarity,
title, author, publisher, price, description
FROM book_openai
ORDER BY sem_vec ANN OF %s LIMIT 5;
"""
)

results = session.execute(query, (emb_query, emb_query))
for row in results:
  print(row)

Row(similarity=0.9494473934173584, title='量子コンピューティング入門', author='岡本太郎', publisher='技術書典', price=5800, description='量子コンピューティングの基礎理論から実践的な応用までを解説。')
Row(similarity=0.9434530735015869, title='量子コンピュータ応用', author='田島美和', publisher='技術書典', price=4900, description='量子コンピュータの応用領域と実践的な利用事例に焦点を当てたガイド。')
Row(similarity=0.9098890423774719, title='クラウドセキュリティベストプラクティス', author='西村さゆり', publisher='技術出版株式会社', price=4700, description='クラウド環境でのセキュリティのベストプラクティスを解説。')
Row(similarity=0.9098612666130066, title='Python機械学習実践ガイド', author='西村美和', publisher='技術書典', price=5300, description='Pythonを使用した機械学習の基本理論から実践的な応用までを解説。')
Row(similarity=0.9093129634857178, title='データウェアハウス最適化', author='田口健太', publisher='技術書典', price=4700, description='データウェアハウスの最適化手法とパフォーマンスチューニングに関する実践的な知識。')


## LangChain

In [ ]:
from cassandra.cluster import Session
from cassandra.query import PreparedStatement
class AstraBookRetriever(BaseRetriever):
    session: Session
    embedding: OpenAIEmbeddings
    lang: str = "Japanese"
    search_statement_ja: PreparedStatement = None

    class Config:
        arbitrary_types_allowed = True

    def get_relevant_documents(self, query):
        docs = []
        embeddingvector = self.embedding.embed_query(query)
        if self.search_statement_ja is None:
            self.search_statement_ja = self.session.prepare("""
                SELECT
                    id,
                    similarity_cosine(sem_vec, ?) as similarity,
                    title,
                    author,
                    publisher,
                    price,
                    description
                FROM bookstore.book_openai
                ORDER BY sem_vec ANN OF ?
                LIMIT ?
                """)
        query = self.search_statement_ja
        results = self.session.execute(query, [embeddingvector, embeddingvector, 5])
        top_products = results._current_rows
        for r in top_products:
            if r.similarity > 0.91:
                docs.append(Document(
                    id=r.id,
                    page_content=r.title,
                    metadata={"id": r.id,
                            "title": r.title,
                            "author": r.author,
                            "publisher": r.publisher,
                            "description": r.description,
                            "price": r.price
                            }
                ))

        return docs

In [ ]:
def create_chatbot(lang: str, Session: session):
    print(f"Creating chatbot for {lang}...")
    llm = ChatOpenAI(temperature=0, streaming=True)
    embedding = OpenAIEmbeddings()

    retriever = AstraBookRetriever(
        session=session, embedding=embedding, lang=lang)
    retriever_tool = create_retriever_tool(
        retriever, "books_retrevier", "Useful when searching for books from a book store. Prices are in YEN.")
    system_message = """
    You are a customer service of a book store and you are asked to pick books for a customer.
    You must try to find books related to given questions first.
    You must use the books_retreiver.
    You must not provide any information other than books that you get from books_retriever.
    You should behave as a bookstore clerk.
    """
    if lang == "Japanese":
        system_message = f"{system_message} All the responses should be in Japanese language."
    message = SystemMessage(content=system_message)
    agent_executor = create_conversational_retrieval_agent(
        llm=llm, tools=[retriever_tool], system_message=message, verbose=True)
    return agent_executor


In [ ]:
lang = "Japanese"
chatbot = create_chatbot(lang, session)

Creating chatbot for Japanese...


In [ ]:
prompt = "量子コンピュータについての本を教えて"
result = chatbot.invoke({
            "input": prompt})
print(result["output"])

[chain/start] [1:chain:AgentExecutor] Entering Chain run with input:
{
  "input": "量子コンピュータについての本を教えて",
  "chat_history": []
}
[llm/start] [1:chain:AgentExecutor > 2:llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: \n    You are a customer service of a book store and you are asked to pick books for a customer.\n    You must try to find books related to given questions first.\n    You must use the books_retreiver.\n    You must not provide any information other than books that you get from books_retriever.\n    You should behave as a bookstore clerk.\n     All the responses should be in Japanese language.\nHuman: 量子コンピュータについての本を教えて"
  ]
}
[llm/end] [1:chain:AgentExecutor > 2:llm:ChatOpenAI] [2.76s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "",
        "generation_info": {
          "finish_reason": "function_call"
        },
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
         

# Part B: LangChain with CassIO

In [ ]:
!pip install cassio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.1/40.1 kB 1.4 MB/s eta 0:00:00


In [ ]:
from langchain.vectorstores import Cassandra

In [ ]:
YOUR_KEYSPACE = 'cassio'
session.set_keyspace(YOUR_KEYSPACE)
session

In [ ]:
TABLE_NAME = "cassio_books"
vectorstore = Cassandra(embeddings, session, YOUR_KEYSPACE, TABLE_NAME)

In [ ]:
df

ID                title author   publisher  price  year  \
0      1       ネットワークセキュリティ入門   山田太郎        技術書典   4500  2021   
1      2         ビジネスデータ分析の基礎   田中花子    ビジネスブックス   3800  2020   
2      3      クラウドアーキテクチャデザイン   鈴木次郎    技術出版株式会社   5500  2022   
3      4          金融取引のアルゴリズム    林美香      データ出版社   5200  2019   
4      5          人事マネジメントの実践   佐藤健太  ビジネスパートナーズ   4800  2020   
..   ...                  ...    ...         ...    ...   ...   
98    99       サプライチェーンマネジメント   中村健太      データ出版社   5200  2022   
99   100           量子コンピュータ応用   田島美和        技術書典   4900  2020   
100  101      エンタープライズアーキテクチャ   小林花子  ビジネスパートナーズ   4400  2019   
101  102  プロジェクトポートフォリオマネジメント   松井直樹    技術出版株式会社   5000  2020   
102  103         マネジメント情報システム   大木美和     データブックス   4600  2021   

                                         description  
0                ネットワークセキュリティの基本原則と実践的な手法に焦点を当てた入門書。  
1                   ビジネスにおけるデータ分析の基本的な手法とツールの使い方を解説。  
2    クラウドネイティブなアプリケーションのアーキテクチャデザインとベストプラクティスを詳細に解説。  
3     金融市場におけるアルゴリズムトレーディングの基本原則と実践手法に焦点を当てた実践的なガイド。  
4                  組織内の人材マネジメントに関する基本的な原則と実践的な手法を紹介。  
..                                               ...  
98                    効果的なサプライチェーンマネジメントの原則と実践手法を解説。  
99                 量子コンピュータの応用領域と実践的な利用事例に焦点を当てたガイド。  
100             エンタープライズ全体のアーキテクチャ設計と最適化手法に関する実践ガイド。  
101               プロジェクトポートフォリオの戦略的なマネジメント手法と実践例を解説。  
102               組織内でのマネジメント情報システムの設計と運用に焦点を当てたガイド。  

[103 rows x 7 columns]

In [ ]:
id_series = df["ID"]
ids = id_series.to_list()
type(ids)

list

In [ ]:
texts = targets
type(texts)

list

In [ ]:
ids

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103]

In [ ]:
df_for_meta = df.drop(['ID','description'], axis=1)
df_for_meta

title author   publisher  price  year
0         ネットワークセキュリティ入門   山田太郎        技術書典   4500  2021
1           ビジネスデータ分析の基礎   田中花子    ビジネスブックス   3800  2020
2        クラウドアーキテクチャデザイン   鈴木次郎    技術出版株式会社   5500  2022
3            金融取引のアルゴリズム    林美香      データ出版社   5200  2019
4            人事マネジメントの実践   佐藤健太  ビジネスパートナーズ   4800  2020
..                   ...    ...         ...    ...   ...
98        サプライチェーンマネジメント   中村健太      データ出版社   5200  2022
99            量子コンピュータ応用   田島美和        技術書典   4900  2020
100      エンタープライズアーキテクチャ   小林花子  ビジネスパートナーズ   4400  2019
101  プロジェクトポートフォリオマネジメント   松井直樹    技術出版株式会社   5000  2020
102         マネジメント情報システム   大木美和     データブックス   4600  2021

[103 rows x 5 columns]

In [ ]:
metadatas = df_for_meta.to_dict(orient='records')
metadatas[0]

{'title': 'ネットワークセキュリティ入門',
 'author': '山田太郎',
 'publisher': '技術書典',
 'price': 4500,
 'year': 2021}

In [ ]:
vectorstore.aadd_texts(texts, metadatas)

<coroutine object VectorStore.aadd_texts at 0x7b1a35c5b290>

```
token@cqlsh:cassio> desc tables;

cassio_books

token@cqlsh:cassio> desc cassio_books;

CREATE TABLE cassio.cassio_books (
    row_id text PRIMARY KEY,
    attributes_blob text,
    body_blob text,
    metadata_s map<text, text>,
    vector vector<float, 1536>
) WITH additional_write_policy = '99p'
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.UnifiedCompactionStrategy'}
    AND compression = {'chunk_length_in_kb': '16', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair = 'BLOCKING'
    AND speculative_retry = '99p';
CREATE CUSTOM INDEX eidx_metadata_s_cassio_books ON cassio.cassio_books (entries(metadata_s)) USING 'org.apache.cassandra.index.sai.StorageAttachedIndex';
CREATE CUSTOM INDEX idx_vector_cassio_books ON cassio.cassio_books (vector) USING 'org.apache.cassandra.index.sai.StorageAttachedIndex';
```

In [ ]:
await vectorstore.aadd_texts(texts, metadatas)

['948d38d32fb54b7da4d4e8a6f07d3fb9',
 'e6359fa863484bc18583cf2b2808c05e',
 '0071b0e56a624e0c86811dfa5157ef39',
 'de4f221af321476cb24b22be8f71dda2',
 'f49bfd7be9e2413d84e66612777a4ca2',
 '352825ae6f7a45f6b30e37390e9c3def',
 'c3d08de58fb8459f81cbc9e76338f2f0',
 '790424d750e843008585193e3f95e25c',
 'f58a31a5502f488796a539afae2248cc',
 '9a2fbc3d324e4e6b85a9e2fb789382e7',
 '16d75fb24e7844e7b4bc0f339bc34b2b',
 '6e2792e35f6d4fe5974f3c3c88900016',
 'bd4199d8358949fc945fdead4a52d6e1',
 '14bbab8a49e54a158edd8d7c6fd232ee',
 '42fc0e534c04499eac2c2572ff922187',
 '01989c4fb0184192b77c1cee69987d84',
 '65c21e790ab04a94ac5b8205955649f0',
 '2db168a5a875462092c6ff3f9eb92f4f',
 '33a6c3793e154b9caf81fe846ccca920',
 '8a7c58f08328429491abd1f657a740ca',
 '376c3377fc1f426abb7df14506edbda6',
 '653e9147c5904362802db6d8abeb7340',
 '8897dd7b14814d74a13c7c06c877bbb1',
 '9140eecfe4b14337a28364f3f1e6f571',
 '84c10d44ad5747c3abff92c597035985',
 '0425548f07694b7d98ef3848506d4f9e',
 'c14f85a7dce24976ae65229f77e85dd2',
 

```
token@cqlsh:cassio> select row_id, metadata_s from cassio_books limit 1;

 row_id                           | metadata_s
----------------------------------+---------------------------------------------------------------------------------------------------------------------------
 de4f221af321476cb24b22be8f71dda2 | {'author': '林美香', 'price': '5200.0', 'publisher': 'データ出版社', 'title': '金融取引のアルゴリズム', 'year': '2019.0'}

(1 rows)
```

```
token@cqlsh:cassio> select row_id, attributes_blob, body_blob from cassio_books limit 1;

 row_id                           | attributes_blob | body_blob
----------------------------------+-----------------+----------------------------------------------------------------------------------------------
 de4f221af321476cb24b22be8f71dda2 |            null | 金融市場におけるアルゴリズムトレーディングの基本原則と実践手法に焦点を当てた実践的なガイド。
```

In [ ]:
TABLE_NAME_WITH_ID = "cassio_books_with_id"
vectorstore_with_id = Cassandra(embeddings, session, YOUR_KEYSPACE, TABLE_NAME_WITH_ID)

```
token@cqlsh:cassio> desc cassio_books_with_id;

CREATE TABLE cassio.cassio_books_with_id (
    row_id text PRIMARY KEY,
    attributes_blob text,
    body_blob text,
    metadata_s map<text, text>,
    vector vector<float, 1536>
) WITH additional_write_policy = '99p'
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.UnifiedCompactionStrategy'}
    AND compression = {'chunk_length_in_kb': '16', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair = 'BLOCKING'
    AND speculative_retry = '99p';
CREATE CUSTOM INDEX eidx_metadata_s_cassio_books_with_id ON cassio.cassio_books_with_id (entries(metadata_s)) USING 'org.apache.cassandra.index.sai.StorageAttachedIndex';
CREATE CUSTOM INDEX idx_vector_cassio_books_with_id ON cassio.cassio_books_with_id (vector) USING 'org.apache.cassandra.index.sai.StorageAttachedIndex';

```

In [ ]:
str_ids = [str(i) for i in ids]

In [ ]:
vectorstore_with_id.add_texts(texts, metadatas, str_ids)

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '70',
 '71',
 '72',
 '73',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '80',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '90',
 '91',
 '92',
 '93',
 '94',
 '95',
 '96',
 '97',
 '98',
 '99',
 '100',
 '101',
 '102',
 '103']

In [ ]:
ids

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103]

```
token@cqlsh:cassio> select row_id, metadata_s from cassio_books_with_id limit 1;

 row_id | metadata_s
--------+---------------------------------------------------------------------------------------------------------------------
      6 | {'author': '伊藤さやか', 'price': '4200.0', 'publisher': '技術書典', 'title': '自然言語処理入門', 'year': '2021.0'}

(1 rows)
token@cqlsh:cassio> select row_id, attributes_blob, body_blob from cassio_books_with_id limit 1;

 row_id | attributes_blob | body_blob
--------+-----------------+------------------------------------------------------------------------
      6 |            null | 自然言語処理の基本概念から、実践的なテキストデータ処理手法までを解説。

(1 rows)
```

In [ ]:
retriever_from_cassio = vectorstore_with_id.as_retriever()

In [ ]:
def create_chatbot_with_retriever(lang: str, session, retriever):
    print(f"Creating chatbot for {lang}...")
    llm = ChatOpenAI(temperature=0, streaming=True)
    embedding = OpenAIEmbeddings()

    retriever_tool = create_retriever_tool(
        retriever, "book_retrevier", "Useful when searching for books from a book store. Prices are in YEN.")
    system_message = """
    You are a customer service of a book store and you are asked to pick books for a customer.
    You must try to find books related to given questions first.
    You must use the books_retreiver.
    You must not provide any information other than books that you get from books_retriever.
    You should behave as a bookstore clerk.
    """
    if lang == "Japanese":
        system_message = f"{system_message} All the responses should be in Japanese language."
    message = SystemMessage(content=system_message)
    agent_executor = create_conversational_retrieval_agent(
        llm=llm, tools=[retriever_tool], system_message=message, verbose=True)
    return agent_executor

In [ ]:
lang = "Japanese"
chatbot_cassio = create_chatbot_with_retriever(lang, session, retriever_from_cassio)

Creating chatbot for Japanese...


In [ ]:
prompt = "機械学習についての本を教えて"
result = chatbot_cassio.invoke({
            "input": prompt})
print(result["output"])

[chain/start] [1:chain:AgentExecutor] Entering Chain run with input:
[inputs]
[llm/start] [1:chain:AgentExecutor > 2:llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: \n    You are a customer service of a book store and you are asked to pick books for a customer.\n    You must try to find books related to given questions first.\n    You must use the books_retreiver.\n    You must not provide any information other than books that you get from books_retriever.\n    You should behave as a bookstore clerk.\n     All the responses should be in Japanese language.\nHuman: 量子コンピュータについての本を教えて\nAI: {'name': 'book_retrevier', 'arguments': '{\\n\"__arg1\": \"量子コンピュータ\"\\n}'}\nFunction: [Document(page_content='量子コンピューティングの基礎理論から実践的な応用までを解説。', metadata={'author': '岡本太郎', 'price': '5800.0', 'publisher': '技術書典', 'title': '量子コンピューティング入門', 'year': '2022.0'}), Document(page_content='量子コンピュータの応用領域と実践的な利用事例に焦点を当てたガイド。', metadata={'author': '田島美和', 'price': '4900.0', 'publisher': '技

In [ ]:
vectorstore_with_id.similarity_search(prompt)

[Document(page_content='機械学習プロジェクトの計画と実行に関する手法を解説。', metadata={'author': '田村徹', 'price': '4900.0', 'publisher': '技術出版株式会社', 'title': '機械学習プロジェクト管理', 'year': '2019.0'}),
 Document(page_content='Pythonを使用した機械学習の基本理論から実践的な応用までを解説。', metadata={'author': '西村美和', 'price': '5300.0', 'publisher': '技術書典', 'title': 'Python機械学習実践ガイド', 'year': '2021.0'}),
 Document(page_content='機械学習モデルの解釈手法とモデルの透明性向上に焦点を当てた実践書。', metadata={'author': '高木健太', 'price': '4600.0', 'publisher': '技術書典', 'title': '機械学習モデル解釈', 'year': '2019.0'}),
 Document(page_content='Pythonを使用したデータサイエンスの基本と実践手法を学ぶ。', metadata={'author': '田中健太', 'price': '4200.0', 'publisher': '技術書典', 'title': 'Pythonデータサイエンス', 'year': '2020.0'})]

In [ ]:
vectorstore_with_id.similarity_search_with_relevance_scores(prompt)

[(Document(page_content='機械学習プロジェクトの計画と実行に関する手法を解説。', metadata={'author': '田村徹', 'price': '4900.0', 'publisher': '技術出版株式会社', 'title': '機械学習プロジェクト管理', 'year': '2019.0'}),
  0.9582059882122543),
 (Document(page_content='Pythonを使用した機械学習の基本理論から実践的な応用までを解説。', metadata={'author': '西村美和', 'price': '5300.0', 'publisher': '技術書典', 'title': 'Python機械学習実践ガイド', 'year': '2021.0'}),
  0.955012579391338),
 (Document(page_content='機械学習モデルの解釈手法とモデルの透明性向上に焦点を当てた実践書。', metadata={'author': '高木健太', 'price': '4600.0', 'publisher': '技術書典', 'title': '機械学習モデル解釈', 'year': '2019.0'}),
  0.9516094628536547),
 (Document(page_content='自然言語処理と機械翻訳の基本原則と応用手法を学ぶ。', metadata={'author': '山岸直樹', 'price': '5300.0', 'publisher': '技術出版株式会社', 'title': '自然言語処理と機械翻訳', 'year': '2018.0'}),
  0.9452244171689543)]

In [ ]:
vectorstore_with_id.similarity_search_with_relevance_scores(prompt,filter={'publisher':'技術書典'})

[(Document(page_content='Pythonを使用した機械学習の基本理論から実践的な応用までを解説。', metadata={'author': '西村美和', 'price': '5300.0', 'publisher': '技術書典', 'title': 'Python機械学習実践ガイド', 'year': '2021.0'}),
  0.955012579391338),
 (Document(page_content='機械学習モデルの解釈手法とモデルの透明性向上に焦点を当てた実践書。', metadata={'author': '高木健太', 'price': '4600.0', 'publisher': '技術書典', 'title': '機械学習モデル解釈', 'year': '2019.0'}),
  0.9516094628536547),
 (Document(page_content='Pythonを使用したデータサイエンスの基本と実践手法を学ぶ。', metadata={'author': '田中健太', 'price': '4200.0', 'publisher': '技術書典', 'title': 'Pythonデータサイエンス', 'year': '2020.0'}),
  0.9406776871579778),
 (Document(page_content='自然言語処理とテキストマイニングの基本原則と実践手法を学ぶ。', metadata={'author': '村上健太', 'price': '4700.0', 'publisher': '技術書典', 'title': '自然言語処理とテキストマイニング', 'year': '2020.0'}),
  0.9349136561027702)]

In [ ]:
vectorstore_with_id.similarity_search_with_relevance_scores(prompt,filter={'author':'西村美和'})

[(Document(page_content='Pythonを使用した機械学習の基本理論から実践的な応用までを解説。', metadata={'author': '西村美和', 'price': '5300.0', 'publisher': '技術書典', 'title': 'Python機械学習実践ガイド', 'year': '2021.0'}),
  0.9550125793913378)]

In [ ]:
vectorstore_with_id.similarity_search_with_relevance_scores(prompt,filter={'publisher':'技術書典', 'author':'西村美和'})

[(Document(page_content='Pythonを使用した機械学習の基本理論から実践的な応用までを解説。', metadata={'author': '西村美和', 'price': '5300.0', 'publisher': '技術書典', 'title': 'Python機械学習実践ガイド', 'year': '2021.0'}),
  0.9550117525065313)]

In [ ]:
vectorstore_with_id.similarity_search_with_relevance_scores(prompt,filter={'publisher':'技術書典', 'title':'自然言語'})

[]

In [ ]:
vectorstore_with_id.max_marginal_relevance_search(prompt)

[Document(page_content='機械学習プロジェクトの計画と実行に関する手法を解説。', metadata={'author': '田村徹', 'price': '4900.0', 'publisher': '技術出版株式会社', 'title': '機械学習プロジェクト管理', 'year': '2019.0'}),
 Document(page_content='Pythonを使用した機械学習の基本理論から実践的な応用までを解説。', metadata={'author': '西村美和', 'price': '5300.0', 'publisher': '技術書典', 'title': 'Python機械学習実践ガイド', 'year': '2021.0'}),
 Document(page_content='機械学習モデルの解釈手法とモデルの透明性向上に焦点を当てた実践書。', metadata={'author': '高木健太', 'price': '4600.0', 'publisher': '技術書典', 'title': '機械学習モデル解釈', 'year': '2019.0'}),
 Document(page_content='自然言語処理と機械翻訳の基本原則と応用手法を学ぶ。', metadata={'author': '山岸直樹', 'price': '5300.0', 'publisher': '技術出版株式会社', 'title': '自然言語処理と機械翻訳', 'year': '2018.0'})]

In [ ]:
vectorstore_with_id.max_marginal_relevance_search(prompt, lambda_mult=0.1)

[Document(page_content='機械学習プロジェクトの計画と実行に関する手法を解説。', metadata={'author': '田村徹', 'price': '4900.0', 'publisher': '技術出版株式会社', 'title': '機械学習プロジェクト管理', 'year': '2019.0'}),
 Document(page_content='自然言語処理とテキストマイニングの基本原則と実践手法を学ぶ。', metadata={'author': '村上健太', 'price': '4700.0', 'publisher': '技術書典', 'title': '自然言語処理とテキストマイニング', 'year': '2020.0'}),
 Document(page_content='データサイエンスにおける統計学の基本と高度な手法までを解説。', metadata={'author': '小林太郎', 'price': '4400.0', 'publisher': 'データ書典', 'title': 'データサイエンティストのための統計学', 'year': '2020.0'}),
 Document(page_content='量子コンピューティングの基礎理論から実践的な応用までを解説。', metadata={'author': '岡本太郎', 'price': '5800.0', 'publisher': '技術書典', 'title': '量子コンピューティング入門', 'year': '2022.0'})]

In [ ]:
vectorstore_with_id.max_marginal_relevance_search(prompt, lambda_mult=0.9)

[Document(page_content='機械学習プロジェクトの計画と実行に関する手法を解説。', metadata={'author': '田村徹', 'price': '4900.0', 'publisher': '技術出版株式会社', 'title': '機械学習プロジェクト管理', 'year': '2019.0'}),
 Document(page_content='Pythonを使用した機械学習の基本理論から実践的な応用までを解説。', metadata={'author': '西村美和', 'price': '5300.0', 'publisher': '技術書典', 'title': 'Python機械学習実践ガイド', 'year': '2021.0'}),
 Document(page_content='機械学習モデルの解釈手法とモデルの透明性向上に焦点を当てた実践書。', metadata={'author': '高木健太', 'price': '4600.0', 'publisher': '技術書典', 'title': '機械学習モデル解釈', 'year': '2019.0'}),
 Document(page_content='自然言語処理と機械翻訳の基本原則と応用手法を学ぶ。', metadata={'author': '山岸直樹', 'price': '5300.0', 'publisher': '技術出版株式会社', 'title': '自然言語処理と機械翻訳', 'year': '2018.0'})]

In [ ]:
# Retrieve more documents with higher diversity
# Useful if your dataset has many similar documents
retriever_a = vectorstore_with_id.as_retriever(
    search_type="mmr",
    search_kwargs={'k': 6, 'lambda_mult': 0.25}
)

# Fetch more documents for the MMR algorithm to consider
# But only return the top 5
retriever_b = vectorstore_with_id.as_retriever(
    search_type="mmr",
    search_kwargs={'k': 5, 'fetch_k': 50}
)

# Only retrieve documents that have a relevance score
# Above a certain threshold
retriever_c = vectorstore_with_id.as_retriever(
    search_type="similarity_score_threshold",
    search_kwargs={'score_threshold': 0.95}
)

# Only get the single most similar document from the dataset
retriever_d = vectorstore_with_id.as_retriever(search_kwargs={'k': 1})

# Use a filter to only retrieve documents from a specific paper
retriever_e = vectorstore_with_id.as_retriever(
    search_kwargs={'filter': {'paper_title':'GPT-4 Technical Report'}}
)